services:
  - type: web
    name: chatbot-backend
    env: python
    plan: free
    pythonVersion: 3.9
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn api.index:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GROQ_API_KEY
        scope: run
        sync: fals